apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop
  namespace: dev
data:
  CATALOGUE_HOST: catalogue
  AMQP_HOST: rabbitmq
  CART_HOST: cart
  CART_PORT: "8080"
  USER_HOST: user
  USER_PORT: "8080"
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
  REDIS_HOST: redis-master
